export interface MetricMethodology {
  title: string;
  measures: string;
  formula: string;
  method: string;
  classification: "Exact" | "Derived";
  limitations: string;
}

export const METHODOLOGY_DICTIONARY: Record<string, MetricMethodology> = {
  "Total messages": {
    title: "Total Messages",
    measures: "The total number of non-system messages parsed from the chat export.",
    formula: "count(all valid sender messages)",
    method: "Each parsed line with a timestamp and valid sender is counted as 1 message.",
    classification: "Exact",
    limitations: "System notifications (e.g. key changes, group joins) are excluded from the total.",
  },
  "Messages counted": {
    title: "Messages Counted",
    measures: "Total message volume recorded across active calendar days.",
    formula: "sum(messages)",
    method: "Extracted from valid message timestamps.",
    classification: "Exact",
    limitations: "Measures parsed messages in this export.",
  },
  "Total words": {
    title: "Total Words",
    measures: "The sum of all words typed across all messages.",
    formula: "sum(wordCount per message)",
    method: "Unicode-aware tokenization splits text on whitespace and word boundaries.",
    classification: "Exact",
    limitations: "Punctuation marks and standalone symbols are excluded from word count.",
  },
  "Active days": {
    title: "Active Days",
    measures: "The number of unique calendar dates with at least one recorded message.",
    formula: "count(distinct local dates)",
    method: "Message timestamps are converted to local YYYY-MM-DD calendar keys and deduplicated.",
    classification: "Exact",
    limitations: "Days with 0 messages are not counted as active days.",
  },
  "Conversation count": {
    title: "Conversation Count",
    measures: "The total number of distinct conversation sessions in this export.",
    formula: "1 + count(message time gaps > 30 minutes)",
    method: "Messages are ordered chronologically. A new session begins whenever the gap between consecutive messages exceeds 30 minutes.",
    classification: "Derived",
    limitations: "Session boundaries use a 30-minute idle threshold rule, not an explicit conversation start/stop tag.",
  },
  "Chat span": {
    title: "Chat Span",
    measures: "The total elapsed calendar duration between the first and last message in this export.",
    formula: "lastMessageTimestamp - firstMessageTimestamp",
    method: "Computed by measuring exact years, months, and days between earliest and latest message timestamps.",
    classification: "Exact",
    limitations: "Does not reflect whether chatting was continuous throughout the span.",
  },
  "Message share": {
    title: "Message Share",
    measures: "The proportion of total messages sent by each participant.",
    formula: "(participantMessages / totalMessages) * 100",
    method: "Messages are grouped by sender name and divided by the total message count.",
    classification: "Exact",
    limitations: "Counts message count, not word count or message length.",
  },
  "Busiest day": {
    title: "Busiest Day",
    measures: "The single calendar date with the highest recorded message volume.",
    formula: "date with max(dailyMessageCount)",
    method: "Daily message counts are aggregated into date buckets to find the peak volume date.",
    classification: "Exact",
    limitations: "Reflects message volume on a single local calendar date.",
  },
  "Quietest day": {
    title: "Quietest Day",
    measures: "The active calendar date with the lowest non-zero message volume.",
    formula: "date with min(dailyMessageCount where count > 0)",
    method: "Filters active calendar dates to find the lowest message count recorded.",
    classification: "Exact",
    limitations: "Days with 0 messages are excluded.",
  },
  "Weekend share": {
    title: "Weekend Share",
    measures: "The percentage of total messages sent on Saturdays and Sundays.",
    formula: "((saturdayMsgs + sundayMsgs) / totalMessages) * 100",
    method: "Message timestamps are mapped to local day-of-week indexes (Saturday = 6, Sunday = 0).",
    classification: "Derived",
    limitations: "Based on local timezone calendar days.",
  },
  "Peak hour": {
    title: "Peak Hour",
    measures: "The 1-hour time window (00:00 to 23:00) with the highest total message volume.",
    formula: "hour with max(hourlyMessageCount)",
    method: "Message timestamps are bucketed by their local hour (0 to 23).",
    classification: "Derived",
    limitations: "Aggregates message volume across all recorded days.",
  },
  "Activity calendar": {
    title: "Activity Calendar",
    measures: "Daily message density across calendar dates.",
    formula: "dailyMessageCount for each YYYY-MM-DD",
    method: "Each tile represents a calendar date, color-coded by message count scale.",
    classification: "Exact",
    limitations: "Tiles represent local calendar dates.",
  },
  "24-hour volume": {
    title: "24-Hour Volume",
    measures: "Message distribution across each hour of the day.",
    formula: "sum(messages) for hour in 0..23",
    method: "Buckets every message by its local hour timestamp.",
    classification: "Derived",
    limitations: "Combines data from all days into a 24-hour clock profile.",
  },
  "Time of day": {
    title: "Time of Day Distribution",
    measures: "Messages grouped into three standard time periods: morning, afternoon, and night.",
    formula: "Morning (06:00 to 11:59), Afternoon (12:00 to 17:59), Night (18:00 to 05:59)",
    method: "Aggregates messages into three time of day buckets sorted in descending order of volume.",
    classification: "Derived",
    limitations: "Uses fixed time intervals (Morning 06:00 to 11:59, Afternoon 12:00 to 17:59, Night 18:00 to 05:59).",
  },
  "Who starts it?": {
    title: "Session Initiator Share",
    measures: "The percentage of 30-minute conversation sessions initiated by each participant.",
    formula: "(participantInitiations / totalSessions) * 100",
    method: "Identifies the sender of the first message in each derived 30-minute gap session.",
    classification: "Derived",
    limitations: "Session initiation depends on the 30-minute idle threshold.",
  },
  "Average session": {
    title: "Average Session Length",
    measures: "The average (mean) number of messages per conversation session.",
    formula: "totalMessages / conversationCount",
    method: "Divides total messages by total derived 30-minute gap sessions.",
    classification: "Derived",
    limitations: "Mean values can be skewed by long chat marathons.",
  },
  "Median session": {
    title: "Median Session Length",
    measures: "The median number of messages per conversation session.",
    formula: "median(sessionMessageCounts)",
    method: "Sorts all session message counts and selects the middle value.",
    classification: "Derived",
    limitations: "Protects against skewing from extreme outlier conversations.",
  },
  "Burst distribution": {
    title: "Burst Distribution",
    measures: "The frequency of consecutive messages sent by one participant before a turn change.",
    formula: "count(consecutiveMessagesBySender)",
    method: "Groups consecutive messages from the same sender into burst length buckets.",
    classification: "Derived",
    limitations: "A burst ends as soon as another participant sends a message.",
  },
  "Median reply": {
    title: "Median Response Time",
    measures: "The median elapsed time before a reply is sent after a participant turn change.",
    formula: "median(responseIntervals)",
    method: "Measures elapsed time between the end of one sender's run and the first reply message from another sender.",
    classification: "Derived",
    limitations: "Measures elapsed time only; cannot determine if a reply was expected.",
  },
  "Average reply": {
    title: "Average Response Time",
    measures: "The average (mean) response time between turn changes.",
    formula: "mean(responseIntervals)",
    method: "Sum of all response intervals divided by total turn changes.",
    classification: "Derived",
    limitations: "Can be inflated by overnight delays or extended pauses.",
  },
  "Fastest reply": {
    title: "Fastest Response Time",
    measures: "The shortest recorded response interval between turn changes.",
    formula: "min(responseIntervals)",
    method: "Identifies the minimum elapsed milliseconds between consecutive turns.",
    classification: "Derived",
    limitations: "Measures exact timestamp differences down to the second.",
  },
  "Longest gap": {
    title: "Longest Gap",
    measures: "The maximum recorded idle duration between consecutive message turns.",
    formula: "max(responseIntervals)",
    method: "Identifies the largest time interval between message runs.",
    classification: "Derived",
    limitations: "Reflects the longest pause between participant turns.",
  },
  "Response time distribution": {
    title: "Response Time Distribution",
    measures: "The frequency of response intervals categorized into elapsed time buckets.",
    formula: "count(responseIntervals in bucket)",
    method: "Groups response intervals into buckets (<1m, 1 to 5m, 5 to 15m, etc.).",
    classification: "Derived",
    limitations: "Buckets measure elapsed clock time between turn changes.",
  },
  "Response volume by hour": {
    title: "Response Volume by Hour",
    measures: "The number of turn response messages sent during each hour of the 24-hour clock.",
    formula: "count(responseIntervals in hour 0..23)",
    method: "Buckets every turn response by the local hour of the response timestamp.",
    classification: "Derived",
    limitations: "Shows response activity rhythms throughout the day.",
  },
  "Unique words": {
    title: "Unique Words",
    measures: "The total number of distinct words used in the conversation.",
    formula: "count(distinct normalized words)",
    method: "Converts words to lowercase and counts unique tokens.",
    classification: "Exact",
    limitations: "Case-insensitive; misspellings are counted as distinct words.",
  },
  "Vocab variety": {
    title: "Vocabulary Variety",
    measures: "The number of distinct words used per 1,000 words spoken.",
    formula: "(uniqueWords / totalWords) * 1000",
    method: "Standardizes vocabulary richness to a ratio per 1,000 words.",
    classification: "Derived",
    limitations: "Higher values indicate more varied vocabulary usage.",
  },
  "Avg words/msg": {
    title: "Average Words Per Message",
    measures: "The average (mean) number of words per message.",
    formula: "totalWords / totalMessages",
    method: "Divides total words by total messages.",
    classification: "Derived",
    limitations: "Includes short messages like 'ok' and long paragraphs.",
  },
  "Most used words": {
    title: "Most Used Words",
    measures: "The most frequently typed words in the export.",
    formula: "topN(wordFrequencies excluding stopwords)",
    method: "Filters out common stop words (e.g. 'the', 'is', 'and') and ranks word frequencies.",
    classification: "Exact",
    limitations: "Stop word filtering removes common functional words.",
  },
  "How much you type": {
    title: "Message Length Breakdown",
    measures: "Average and median word counts per message.",
    formula: "mean(wordsPerMsg) & median(wordsPerMsg)",
    method: "Calculates average and median length across all messages.",
    classification: "Derived",
    limitations: "Reflects typing verbosity.",
  },
  "Questions": {
    title: "Question Detection",
    measures: "Messages containing question marks.",
    formula: "count(messages containing '?')",
    method: "Scans message text for question mark punctuation.",
    classification: "Exact",
    limitations: "Punctuation-based detection only; rhetorical or unpunctuated questions are not inferred.",
  },
  "Total emojis": {
    title: "Total Emojis",
    measures: "The total count of all emojis used across all messages.",
    formula: "sum(emojiCount per message)",
    method: "Parses visible emoji grapheme clusters, including composite and skin-tone emojis.",
    classification: "Exact",
    limitations: "Counts each individual emoji symbol.",
  },
  "Messages w/ emoji": {
    title: "Messages Containing Emojis",
    measures: "The percentage of messages that contain at least one emoji.",
    formula: "(messagesWithEmoji / totalMessages) * 100",
    method: "Counts messages with emojiCount > 0 divided by total messages.",
    classification: "Derived",
    limitations: "Measures message prevalence, not total emoji count.",
  },
  "Avg emojis/msg": {
    title: "Average Emojis Per Message",
    measures: "The average number of emojis per message when emojis are used.",
    formula: "totalEmojis / totalMessages",
    method: "Divides total emojis by total messages.",
    classification: "Derived",
    limitations: "Reflects emoji density.",
  },
  "Most used emoji": {
    title: "Most Used Emoji",
    measures: "The single emoji character with the highest total count.",
    formula: "emoji with max(frequencyCount)",
    method: "Counts exact emoji character occurrences.",
    classification: "Exact",
    limitations: "Identifies top symbol.",
  },
  "The leaderboard": {
    title: "Emoji Leaderboard",
    measures: "Top emoji characters ranked by usage count.",
    formula: "topN(emojiCounts)",
    method: "Aggregates and ranks all parsed emoji symbols.",
    classification: "Exact",
    limitations: "Ranks frequency of visible emoji characters.",
  },
  "Total links": {
    title: "Total Links Shared",
    measures: "The total number of URLs detected in message texts.",
    formula: "count(extracted URLs)",
    method: "Extracts web URLs matching URL pattern regex.",
    classification: "Exact",
    limitations: "TexTale does not fetch or load external web pages.",
  },
  "Unique domains": {
    title: "Unique Web Domains",
    measures: "The number of distinct website hostnames shared.",
    formula: "count(distinct hostnames)",
    method: "Extracts domain hostnames from URLs and deduplicates.",
    classification: "Exact",
    limitations: "Subdomains are grouped by primary hostname.",
  },
  "Who shares more": {
    title: "Links Shared By Participant",
    measures: "Link sharing volume and percentage breakdown by participant.",
    formula: "(participantLinks / totalLinks) * 100",
    method: "Counts URLs extracted from each participant's messages.",
    classification: "Exact",
    limitations: "Counts URL occurrences per sender.",
  },
  "Longest conversation": {
    title: "Longest Conversation Session",
    measures: "The single 30-minute gap session with the longest time duration.",
    formula: "max(session.durationMs)",
    method: "Finds the session with the maximum elapsed milliseconds between start and end.",
    classification: "Derived",
    limitations: "Session boundaries use 30-minute idle gaps.",
  },
  "Most words in a day": {
    title: "Most Words in a Day",
    measures: "The single calendar date with the highest word count.",
    formula: "max(dailyWordCount)",
    method: "Aggregates word counts by date to find the peak word volume date.",
    classification: "Exact",
    limitations: "Reflects word volume on a single local calendar date.",
  },
  "Longest streak": {
    title: "Longest Daily Streak",
    measures: "The maximum consecutive active calendar days with message activity.",
    formula: "max(consecutiveActiveDays)",
    method: "Finds the longest uninterrupted sequence of active dates.",
    classification: "Derived",
    limitations: "Requires at least 1 message per day to maintain streak.",
  },
  "Most questions": {
    title: "Most Questions in a Day",
    measures: "The single calendar date with the highest number of question messages.",
    formula: "max(dailyQuestionCount)",
    method: "Aggregates question messages by date to find peak question volume date.",
    classification: "Exact",
    limitations: "Punctuation-based question detection.",
  },
};

export function getMethodology(label: string): MetricMethodology {
  if (METHODOLOGY_DICTIONARY[label]) return METHODOLOGY_DICTIONARY[label];

  // Case-insensitive / partial fallback matching
  const key = Object.keys(METHODOLOGY_DICTIONARY).find(
    (k) => k.toLowerCase() === label.toLowerCase() || label.toLowerCase().includes(k.toLowerCase())
  );

  if (key) return METHODOLOGY_DICTIONARY[key];

  return {
    title: label,
    measures: `${label} calculated from your exported conversation messages.`,
    formula: "Computed locally from parsed timestamps and message texts.",
    method: "Aggregated locally within your browser session.",
    classification: "Exact",
    limitations: "Metrics describe observable text and timestamps only; they do not infer intent.",
  };
}
